// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUgCHV_vgOH-m_W2vbShMRxw1bJaRLEZY',
    appId: '1:314643053617:web:153321f24657cd74d2e910',
    messagingSenderId: '314643053617',
    projectId: 'live-news-app-38536',
    authDomain: 'live-news-app-38536.firebaseapp.com',
    storageBucket: 'live-news-app-38536.appspot.com',
    measurementId: 'G-730KFP28WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsGw7DcauNG2t4UZJVl2iW0dTRPGb47WI',
    appId: '1:314643053617:android:0e0c633169bd46a0d2e910',
    messagingSenderId: '314643053617',
    projectId: 'live-news-app-38536',
    storageBucket: 'live-news-app-38536.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3RqAzv8ZV0bVmJ-ZfGqRuJZAjIyijaeE',
    appId: '1:314643053617:ios:cc99b29e54f46619d2e910',
    messagingSenderId: '314643053617',
    projectId: 'live-news-app-38536',
    storageBucket: 'live-news-app-38536.appspot.com',
    iosClientId: '314643053617-3abdnc974mk506osjnl4f2e5fcji0vhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3RqAzv8ZV0bVmJ-ZfGqRuJZAjIyijaeE',
    appId: '1:314643053617:ios:0e214bd265d7daced2e910',
    messagingSenderId: '314643053617',
    projectId: 'live-news-app-38536',
    storageBucket: 'live-news-app-38536.appspot.com',
    iosClientId: '314643053617-a22majn2acbp7cfsmsh7jjh4pkhp813g.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApp.RunnerTests',
  );
}
